### PR TITLE
Add vertebrae level preview option

### PR DESCRIPTION
**Pull request by yw7**
Introduced a new flag `levels` to preview_jpg.py to extend and dilate segmentation for single voxel segmentations.
Edit inference script to make preview for levels.

whole_amuPAM50016_T1w_sag_0 5_95

### CODE REVIEW

**Comment by NathanMolinier** [comment]
it did not work when I ran
```
totalspineseg_preview_jpg -i raw --levels --segs-dir out_total/step1_levels/ -o out_total/preview/ --image-suffix ""
```

sub-perform01_T2w_sag_0 5

**Comment by yw7** [comment]
> it did not work when I ran
> 
> ```
> totalspineseg_preview_jpg -i raw --levels --segs-dir out_total/step1_levels/ -o out_total/preview/ --image-suffix ""
> ```
> 
> sub-perform01_T2w_sag_0 5

Can you send me the image and the levels segmentation?
Also what command did you use to run totalspineseg?

**Comment by NathanMolinier** [comment]
Indeed, it is only working on 1mm iso images

**Review by NathanMolinier — APPROVED** [review]
Approved

**Pull request merged**
